### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [nzinov/beret#1]
Would you consider publishing it on [Accrescent](https://github.com/accrescent/accrescent); an alternative android app store?

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by sashkent3** [comment]
I have recently published the app on [F-Droid](https://f-droid.org/packages/ru.lksh.beret/) and I feel like that should be enough. Do you have any arguments for Accrescent specifically?

**Comment by shuvashish76** [comment]
Not really, I'm a happy user of F-Droid :)
It's just another FOSS app store, which is in beta stage so maybe not worth for your effort.

**Comment by sashkent3** [comment]
Ok, thanks for the suggestion though.
